---
title: JakeJnx.com
timezone: GMT
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:categories/:name"
    label: portfolio
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author:
  name: Jake Jenkins
  email: dev@jakejnx.com
description: Jake Jenkins is a front end web developer in South Wales, United Kingdom.
baseurl: 
url: https://jakejnx.com
show_excerpts: false
minima:
  date_format: "%b %-d, %Y"
theme: minima
plugins:
- jekyll-seo-tag
