---
title: JakeJnx.com
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:categories/:name"
    label: portfolio
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: portfolio
  values:
    layout: portfolio
author:
  name: Jake Jenkins
  email: dev@jakejnx.com
description: Jake Jenkins is a front end web developer in South Wales, United Kingdom.
baseurl: 
url: https://jakejnx.com
show_excerpts: false
minima:
  date_format: "%b %-d, %Y"
include:
- _headers
theme: minima
plugins:
- jekyll-seo-tag
- jekyll-sitemap
